Repository Koniverse/SubWallet-Extension, pull requests merged in 2022-05, with the labels that each got.

#237 koni/dev/issue-193-195
  packages/extension-koni-ui/src/assets/logo/chaosdao.jpeg
  packages/extension-koni-ui/src/assets/logo/chrwna.png
  packages/extension-koni-ui/src/assets/logo/index.ts
Labels: enhancement

#241 Koni/dev/issue 160
  packages/extension-base/src/background/KoniTypes.ts
  packages/extension-koni-base/src/api/dotsama/balance.ts
  packages/extension-koni-base/src/api/dotsama/registry.ts
  packages/extension-koni-base/src/api/nft/acala_nft/index.ts
  packages/extension-koni-base/src/api/nft/bit.country/index.ts
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/eth_nft/index.ts
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
  packages/extension-koni-base/src/api/nft/index.ts
  packages/extension-koni-base/src/api/nft/karura_nft/index.ts
  packages/extension-koni-base/src/api/nft/nft.ts
  packages/extension-koni-base/src/api/nft/quartz_nft/index.ts
  packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
  packages/extension-koni-base/src/api/nft/statemine_nft/index.ts
  packages/extension-koni-base/src/api/nft/unique_nft/index.ts
  packages/extension-koni-base/src/api/nft/unique_nft/uniqueNftV2.ts
  packages/extension-koni-base/src/api/predefineChainTokens.ts
  packages/extension-koni-base/src/api/web3/defaultEvmToken.ts
  packages/extension-koni-base/src/background/cron.ts
  packages/extension-koni-base/src/background/handlers/Extension.ts
  packages/extension-koni-base/src/background/handlers/State.ts
  packages/extension-koni-base/src/background/handlers/index.ts
  packages/extension-koni-base/src/background/subscription.ts
  packages/extension-koni-base/src/constants.ts
  packages/extension-koni-base/src/stores/CustomEvmToken.ts
  packages/extension-koni-base/src/stores/index.ts
  packages/extension-koni-base/src/utils/utils.ts
  packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalances.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmNft.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmToken.tsx
  packages/extension-koni-ui/src/Popup/Settings/TokenSetting/EvmTokenEdit.tsx
  packages/extension-koni-ui/src/Popup/Settings/TokenSetting/EvmTokenRow.tsx
  packages/extension-koni-ui/src/Popup/Settings/TokenSetting/EvmTokenSetting.tsx
  packages/extension-koni-ui/src/Popup/Settings/index.tsx
  packages/extension-koni-ui/src/Popup/index.tsx
  packages/extension-koni-ui/src/hooks/screen/setting/useFetchEvmToken.ts
  packages/extension-koni-ui/src/hooks/store/useSetupEvmToken.ts
  packages/extension-koni-ui/src/hooks/store/useSetupStore.ts
  packages/extension-koni-ui/src/messaging.ts
  packages/extension-koni-ui/src/stores/EvmToken.ts
  packages/extension-koni-ui/src/stores/TokenConfigParams.ts
  packages/extension-koni-ui/src/stores/index.ts
  packages/extension-koni-ui/src/stores/types.ts
Labels: enhancement

#244 Koni/dev/issue 160
  packages/extension-base/src/background/KoniTypes.ts
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/index.ts
  packages/extension-koni-base/src/api/web3/web3.ts
  packages/extension-koni-base/src/background/handlers/Extension.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/index.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmNft.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmToken.tsx
  packages/extension-koni-ui/src/Popup/index.tsx
  packages/extension-koni-ui/src/messaging.ts
Labels: enhancement

#257 Koni/dev/issue 190
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-ui/src/assets/logo/sakura.svg
Labels: enhancement

#249 Koni/dev/issue 200 194
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/unique_nft/test.spec.ts
  packages/extension-koni-base/src/api/nft/unique_nft/uniqueNftV2.ts
  packages/extension-koni-base/src/background/cron.ts
  packages/extension-koni-base/src/background/handlers/Extension.ts
  packages/extension-koni-base/src/background/subscription.ts
  packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalances.tsx
  packages/extension-koni-ui/src/Popup/Home/Crowdloans/Crowdloans.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollection.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
  packages/extension-koni-ui/src/Popup/Home/Staking/StakingContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/TransactionHistory/TransactionHistory.tsx
  packages/extension-koni-ui/src/Popup/Home/index.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmNft.tsx
  packages/extension-koni-ui/src/Popup/ImportToken/ImportEvmToken.tsx
  packages/extension-koni-ui/src/Popup/Settings/TokenSetting/EvmTokenEdit.tsx
  packages/extension-koni-ui/src/Popup/Settings/TokenSetting/EvmTokenSetting.tsx
  packages/extension-koni-ui/src/Popup/index.tsx
Labels: bug, enhancement

#290 Issue 289 - Fix rmrk ipfs gateway
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
Labels: bug

#320 Minor bug on loading NFT collection preview
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
Labels: bug

#323 Minor bug cause infinite loading on staking screen
  packages/extension-koni-base/src/api/staking/subsquidStaking.ts
Labels: bug
