Repository Koniverse/SubWallet-Extension, pull requests merged in 2022-04, with the labels that each got.

#94 [Account] [Import] [Batch] update UI
  packages/extension-koni-ui/src/Popup/ImportQr.tsx
  packages/extension-koni-ui/src/Popup/RestoreJson.tsx
Labels: enhancement

#96 Support transfer NFT for EVM related chains & support bit.country NFT
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-base/src/api/nft/bit.country/index.ts
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/eth_nft/index.ts
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
  packages/extension-koni-base/src/api/nft/index.ts
  packages/extension-koni-base/src/api/staking/config.ts
  packages/extension-koni-base/src/api/staking/ignore-test.spec.ts
  packages/extension-koni-base/src/api/staking/subsquidStaking.ts
  packages/extension-koni-base/src/api/web3/api-helper/TestERC721Contract.json
  packages/extension-koni-base/src/api/web3/web3.ts
  packages/extension-koni-base/src/background/subscription.ts
  packages/extension-koni-ui/package.json
  packages/extension-koni-ui/src/Popup/Home/Nfts/api/paramsHandler.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/api/transferHandler.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/TransferNftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/types.ts
  packages/extension-koni-ui/src/hooks/screen/home/useFetchNft.ts
  packages/extension-koni-ui/src/hooks/screen/home/useFetchNftTransferExtra.ts
  packages/extension-koni-ui/src/hooks/store/useSetupNft.ts
  yarn.lock
Labels: enhancement

#106 Koni/dev/issue 101
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-ui/src/assets/logo/dolphin.svg
  packages/extension-koni-ui/src/assets/logo/index.ts
  packages/extension-koni-ui/src/assets/logo/mangatax.svg
  packages/extension-koni-ui/src/assets/logo/manta.svg
  packages/extension-koni-ui/src/assets/logo/oak_network.png
  packages/extension-koni-ui/src/util/index.ts
Labels: enhancement

#111 Fix Phala provider and SubSocialX chain name
  packages/extension-koni-base/src/api/endpoints.ts
Labels: bug

#112 [Issue-69] [Issue-107] Update UX home page and import account page
  packages/extension-koni-ui/package.json
  packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalanceDetail/ChainBalanceDetailItem.tsx
  packages/extension-koni-ui/src/Popup/Home/ChainBalances/ChainBalances.tsx
  packages/extension-koni-ui/src/Popup/RestoreJson.tsx
  packages/extension-koni-ui/src/util/dom.ts
  yarn.lock
Labels: enhancement

#121 #44/34/33/92/95 Integrate Astar NFT and refactor code
  packages/extension-base/package.json
  packages/extension-base/src/background/KoniTypes.ts
  packages/extension-koni-base/package.json
  packages/extension-koni-base/src/api/nft/acala_nft/index.ts
  packages/extension-koni-base/src/api/nft/bit.country/index.ts
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/eth_nft/index.ts
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
  packages/extension-koni-base/src/api/nft/index.ts
  packages/extension-koni-base/src/api/nft/karura_nft/index.ts
  packages/extension-koni-base/src/api/nft/nft.ts
  packages/extension-koni-base/src/api/nft/quartz_nft/index.ts
  packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
  packages/extension-koni-base/src/api/nft/statemine_nft/index.ts
  packages/extension-koni-base/src/api/nft/unique_nft/index.ts
  packages/extension-koni-base/src/background/handlers/Extension.ts
  packages/extension-koni-base/src/background/subscription.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/api/paramsHandler.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/api/transferHandler.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/TransferNftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/types.ts
  packages/extension-koni-ui/src/hooks/screen/home/useFetchNft.ts
  packages/extension-koni-ui/src/hooks/screen/home/useFetchNftTransferExtra.ts
  packages/extension-koni-ui/src/messaging.ts
  yarn.lock
Labels: bug, enhancement

#126 #125 - Update Polkadex ParaID
  packages/extension-koni-base/src/api/endpoints.ts
Labels: enhancement

#138 Koni/dev/issue 105 109
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-base/src/api/nft/eth_nft/index.ts
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
  packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollection.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollectionPreview.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/AuthTransfer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/TransferNftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/index.tsx
  packages/extension-koni-ui/src/hooks/screen/home/useFetchNft.ts
  packages/extension-koni-ui/src/util/index.ts
Labels: bug, enhancement

#141 #105: Show warning when not select network during NFT transfer
  packages/extension-koni-ui/src/Popup/Home/Nfts/transfer/TransferNftContainer.tsx
Labels: bug

#142 #102: Fix error fetching NFT on firefox
  packages/extension-koni-base/src/api/nft/rmrk_nft/index.ts
  packages/extension-koni-base/src/constants.ts
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftCollection.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftContainer.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItem.tsx
  packages/extension-koni-ui/src/Popup/Home/Nfts/render/NftItemPreview.tsx
Labels: bug, enhancement

#171 Support Astarnaut and AstarCats NFT on Astar
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
Labels: enhancement

#173 Update new network Apr 16, 2022 #172
  packages/extension-koni-base/build-cjs/api/endpoints.js
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-ui/src/assets/logo/chainx.svg
  packages/extension-koni-ui/src/assets/logo/encointer.svg
  packages/extension-koni-ui/src/assets/logo/index.ts
  packages/extension-koni-ui/src/assets/logo/litmus.png
  packages/extension-koni-ui/src/assets/logo/turing.png
  packages/extension-koni-ui/src/assets/logo/unique.network.svg
  packages/extension-koni-ui/src/util/index.ts
Labels: enhancement

#177 Koni/dev/issue 170
  packages/extension-base/src/background/KoniTypes.ts
  packages/extension-koni-base/src/api/dotsama/balance.ts
  packages/extension-koni-base/src/api/dotsama/registry.ts
  packages/extension-koni-base/src/api/predefineChainTokens.ts
  packages/extension-koni-ui/src/assets/logo/aris.png
  packages/extension-koni-ui/src/assets/logo/bill.svg
  packages/extension-koni-ui/src/assets/logo/csm.png
  packages/extension-koni-ui/src/assets/logo/hko.png
  packages/extension-koni-ui/src/assets/logo/index.ts
  packages/extension-koni-ui/src/assets/logo/kico.png
  packages/extension-koni-ui/src/assets/logo/usdt.svg
Labels: enhancement

#179 Koni/dev/issue 178
  packages/extension-koni-base/src/api/nft/index.ts
  packages/extension-koni-base/src/api/nft/quartz_nft/index.ts
Labels: bug

#181 Fix: Some networks show the wrong group #180
  packages/extension-koni-ui/src/assets/logo/index.ts
Labels: bug

#188 Change IPFS gateway for Astar NFT
  packages/extension-koni-base/src/api/nft/config.ts
  packages/extension-koni-base/src/api/nft/eth_nft/index.ts
Labels: bug

#204 Update Centrifuge Parachain info #203
  packages/extension-koni-base/build-cjs/api/endpoints.js
Labels: enhancement

#210 Koni/dev/issue 209
  packages/extension-koni-base/src/api/endpoints.ts
  packages/extension-koni-base/src/api/nft/eth_nft/utils.ts
  packages/extension-koni-base/src/api/web3/web3.ts
  packages/extension-koni-base/src/background/cron.ts
  packages/extension-koni-base/src/constants.ts
Labels: bug
